### ISSUE TITLE
Unable to leverage real-world .swf trace from PWA

### ISSUE THREAD

**Issue by LANNDS18** [renatolfc/sched-rl-gym#2]
Although I tried to replace the trace generator with one that can load directly load .swf files, the simulation step is extremely slow and unable to be used to train RL agents.

**Comment by renatolfc** [comment]
How are you setting up the environment? If you're using the time-based simulator with SWFs, that's probably the cause of the slowness.

**Comment by LANNDS18** [comment]
I've tried both time-based and event-based and tested on HPC2N, the performance is pretty same

**Comment by renatolfc** [comment]
So you're pretty much extrapolating from N=1?

Have you tried running for a subset of the file? The [SwfGenerator](https://github.com/renatolfc/sched-rl-gym/blob/master/schedgym/workload/trace.py#L101) supports both the `offset` and `length` arguments for loading a window of an SWF.

I'd try using those.

**Comment by LANNDS18** [comment]
Thanks for your reply, can I know what values you set for offset and length arguments? :)
